### ISSUE TITLE
weaver.Run err: Cannot use *T as the type PointerToMain[T]

### ISSUE THREAD

**Issue by yrcs** [ServiceWeaver/onlineboutique#9]
As the title, compiling in Goland 2023.2 reports an error: Cannot use *T as the type PointerToMain[T]

**Comment by mwhittaker** [comment]
Hi @yrcs, can you share the code that produced this error?

**Comment by yrcs** [comment]
> Hi @yrcs, can you share the code that produced this error?

It happend in Goland 2023.2 Remote Development mode.
![image](https://github.com/ServiceWeaver/onlineboutique/assets/24586688/39f92295-3601-41ff-875d-30165f2d75da)

**Comment by yrcs** [comment]
Thank you! I'm using Go v1.21.0 as well. Once I changed line 12 what you recommended everything worked fine!

**Comment by mwhittaker** [comment]
Sweet! @rgrandl was telling me he's seen this in Visual Studio as well. It sounds like maybe the IDEs are just lagging behind and haven't fully caught up to some of the ways Go is doing type inference. Hopefully the bug will fix itself over time.

**Comment by s0xzwasd** [comment]
FFR: https://youtrack.jetbrains.com/issue/GO-15316
